/** !! Do not edit this file !!

SiconosConfig.h is generated by cmake from config.h.cmake
depending on the current configuration, on user options (WITH_...) and on their
availability on your system.
Example : if cmake is executed with WITH_MPI=ON
--> if a proper mpi installation is found on your system, then
 SICONOS_HAS_MPI is on and will be defined in this file.
**/

#ifndef SICONOSCONFIG_H
#define SICONOSCONFIG_H

#define WITH_CMAKE

// -- Siconos components --
#cmakedefine HAVE_SICONOS_EXTERNALS
#cmakedefine HAVE_SICONOS_NUMERICS
#cmakedefine HAVE_SICONOS_KERNEL
#cmakedefine HAVE_SICONOS_CONTROL
#cmakedefine HAVE_SICONOS_MECHANICS
#cmakedefine HAVE_SICONOS_MECHANISMS
#cmakedefine HAVE_SICONOS_IO

// -- Global options --
// 
#cmakedefine SICONOS_USE_MAP_FOR_HASH // Prefer std::map to std::unordered_map 

// -- Blas Lapack config --
// Where does cblas come from? 
#cmakedefine HAS_MKL_CBLAS
#cmakedefine HAS_ACCELERATE // includes also lapack from Accelerate
// mkl stuff.
#cmakedefine WITH_MKL_SPBLAS
#cmakedefine WITH_MKL_PARDISO

// Which Lapack? 
#cmakedefine HAS_MKL_LAPACKE
#cmakedefine HAS_MATLAB_LAPACK

// Which functions are defined in lapack?
// This concerns only functions that are not available in all implementations.
#cmakedefine HAS_LAPACK_dgesvd
#cmakedefine HAS_LAPACK_dtrtrs
#cmakedefine HAS_LAPACK_dgels

// Some definitions required for boost numeric_bindings
#define BOOST_NUMERIC_BINDINGS_BLAS_CBLAS
#if defined(HAS_MKL_CBLAS)
#define BOOST_NUMERIC_BINDINGS_BLAS_MKL
#endif

// -- Optional solvers and tools for numerics --
// Gams stuff
#cmakedefine GAMS_MODELS_SOURCE_DIR "@GAMS_MODELS_SOURCE_DIR@"
#cmakedefine GAMS_MODELS_SHARE_DIR "@GAMS_MODELS_SHARE_DIR@"
#cmakedefine GAMS_DIR "@GAMS_ROOT@"
#cmakedefine HAVE_GAMS_C_API
// - Path solver -
#cmakedefine HAVE_PATHFERRIS
#cmakedefine HAVE_PATHVI
// umfpack solvers
#cmakedefine WITH_UMFPACK
// SuperLU solvers
#cmakedefine WITH_SUPERLU
#cmakedefine WITH_SUPERLU_MT
#cmakedefine WITH_SUPERLU_dist
#cmakedefine WITH_MA57

// - internal timer -
#cmakedefine HAVE_TIME_H
#cmakedefine HAVE_SYS_TIMES_H
#cmakedefine WITH_TIMERS

// - mpi part -
#cmakedefine SICONOS_HAS_MPI

// - cuda
#cmakedefine WITH_GPU
#cmakedefine WITH_CUDA

// - mumps solver -
#cmakedefine WITH_MUMPS

// - fclib interface -
#cmakedefine WITH_FCLIB

// -- Optional parts for mechanics --
#cmakedefine SICONOS_HAS_BULLET
#cmakedefine SICONOS_HAS_OpenCASCADE

// -- Optional parts for io --
#cmakedefine WITH_SERIALIZATION
#cmakedefine HAVE_GENERATION



#endif

