
// List of solvers generated with
//   git grep '^ *SICONOS_[A-Z_]* = [0-9]' | sed 's/.*\(SICONOS_[A-Z_]*\).*/SICONOS_SOLVER_MACRO(\1); \\/' |
//   grep -v NUMERICS_PROBLEM > NonSmoothSolvers/SiconosNumerics_Solvers.h


#undef SICONOS_SOLVER_MACRO
#define SICONOS_REGISTER_SOLVERS() \
SICONOS_SOLVER_MACRO(SICONOS_AVI_CAOFERRIS); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_LEMKE); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_NSGS_SBM); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_PGS); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_CPG); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_LATIN); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_LATIN_W); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_QP); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_NSQP); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_NEWTONMIN); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_NEWTON_FBLSA); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_PSOR); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_RPGS); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_PATH); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_ENUM); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_AVI_CAOFERRIS); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_PIVOT); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_BARD); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_MURTY); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_NEWTON_MINFBLSA); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_PATHSEARCH); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_PIVOT_LUMOD); \
SICONOS_SOLVER_MACRO(SICONOS_LCP_GAMS); \
SICONOS_SOLVER_MACRO(SICONOS_MCP_FB); \
SICONOS_SOLVER_MACRO(SICONOS_MCP_NEWTON_FBLSA); \
SICONOS_SOLVER_MACRO(SICONOS_MCP_NEWTON_MINFBLSA); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_PGS); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_RPGS); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_PSOR); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_RPSOR); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_PATH); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_ENUM); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_SIMPLEX); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_DIRECT_ENUM); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_PATH_ENUM); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_DIRECT_SIMPLEX); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_DIRECT_PATH); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_DIRECT_PATH_ENUM); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_FB); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_DIRECT_FB); \
SICONOS_SOLVER_MACRO(SICONOS_MLCP_PGS_SBM); \
SICONOS_SOLVER_MACRO(SICONOS_NCP_NEWTON_FBLSA); \
SICONOS_SOLVER_MACRO(SICONOS_NCP_NEWTON_MINFBLSA); \
SICONOS_SOLVER_MACRO(SICONOS_NCP_PATHSEARCH); \
SICONOS_SOLVER_MACRO(SICONOS_NCP_PATH); \
SICONOS_SOLVER_MACRO(SICONOS_RELAY_PGS); \
SICONOS_SOLVER_MACRO(SICONOS_RELAY_ENUM); \
SICONOS_SOLVER_MACRO(SICONOS_RELAY_PATH); \
SICONOS_SOLVER_MACRO(SICONOS_RELAY_LEMKE); \
SICONOS_SOLVER_MACRO(SICONOS_RELAY_LATIN); \
SICONOS_SOLVER_MACRO(SICONOS_RELAY_NLGS); \
SICONOS_SOLVER_MACRO(SICONOS_RELAY_AVI_CAOFERRIS); \
SICONOS_SOLVER_MACRO(SICONOS_RELAY_AVI_CAOFERRIS_TEST); \
SICONOS_SOLVER_MACRO(SICONOS_VI_EG); \
SICONOS_SOLVER_MACRO(SICONOS_VI_FPP); \
SICONOS_SOLVER_MACRO(SICONOS_VI_HP); \
SICONOS_SOLVER_MACRO(SICONOS_VI_BOX_QI); \
SICONOS_SOLVER_MACRO(SICONOS_VI_BOX_AVI_LSA);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_NSGS);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_NSGSV);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_PROX);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_TFP);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_NSN_AC);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_DSFP);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_VI_FPP);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_VI_EG);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_HP);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_NCPGlockerFBFixedPoint);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_FPP);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_EG);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_NSN_FB);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_ONECONTACT_NSN_AC);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_ONECONTACT_NSN_AC_GP);              \
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_ONECONTACT_ProjectionOnConeWithDiagonalization);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_ONECONTACT_ProjectionOnCone);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_ONECONTACT_ProjectionOnConeWithLocalIteration);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_ONECONTACT_ProjectionOnConeWithRegularization);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_ONECONTACT_ProjectionOnCylinder);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_ONECONTACT_ProjectionOnCone_velocity);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_NCPGlockerFBNewton); \
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_NCPGlockerFBPATH);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_PGoC);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_DeSaxceFixedPoint);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_GAMS_PATH);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_GAMS_PATHVI);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_GAMS_LCP_PATH);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_GAMS_LCP_PATHVI);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_ONECONTACT_QUARTIC);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_ONECONTACT_QUARTIC_NU);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_GLOBAL_NSGS_WR);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_GLOBAL_NSGSV_WR);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_GLOBAL_PROX_WR);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_GLOBAL_DSFP_WR);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_GLOBAL_TFP_WR);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_GLOBAL_NSGS);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_GLOBAL_NSN_AC_WR);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_GLOBAL_AC);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_GLOBAL_GAMS_PATH);\
SICONOS_SOLVER_MACRO(SICONOS_FRICTION_3D_GLOBAL_GAMS_PATHVI);
