"""Common functions used in all steps of Siconos
documentation generation process.


Siconos is a program dedicated to modeling, simulation and control
 of non smooth dynamical systems.

 Copyright 2024 INRIA.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""

import shutil
import pickle
import textwrap
from pathlib import Path

try:
    import lxml.etree as ET
except ImportError:
    import xml.etree.ElementTree as ET


def build_doxygen_xml_index(xml_path, srcdir):
    """
    Build a mapping:

        header file -> list of doxygen xml files

    using Doxygen XML location information.

    Parameters
    ----------
    xml_path : Path
        Doxygen XML output directory.

    srcdir : Path
        Source directory.

    Returns
    -------
    dict
        Mapping from relative header name to XML files.
    """

    xml_path = Path(xml_path)
    srcdir = Path(srcdir)

    result = {}

    for xmlfile in xml_path.glob("*.xml"):

        # Ignore index.xml
        if xmlfile.name == "index.xml":
            continue

        try:
            root = ET.parse(xmlfile).getroot()
        except ET.ParseError:
            continue

        compound = root.find("compounddef")

        if compound is None:
            continue

        kind = compound.attrib.get("kind")

        if kind not in (
            "class",
            "struct",
            "file",
        ):
            continue

        location = compound.find("location")

        if location is None:
            continue

        filename = location.attrib.get("file")

        if filename is None:
            continue

        filename = Path(filename)

        try:
            filename = filename.relative_to(srcdir)
        except ValueError:
            # Doxygen may already give relative paths
            pass

        filename = filename.as_posix()

        if filename not in result:
            result[filename] = []

        result[filename].append(xmlfile)

    return result


def get_xml_files(header_name, xml_index, srcdir):
    """Return all XML files generated by doxygen for a given header file.

    The returned list contains:
      - the XML file describing the header
      - XML files describing classes and structs declared in this header

    The function relies on Doxygen index.xml instead of rebuilding XML
    filenames from the header name. This handles namespaces, included files
    and Doxygen refid naming rules.

    Parameters
    ----------
    header_name : Path()
        header file.
    xml_path : Path()
        absolute path to xml files.

    Returns a list of xml files (Path()).
    """
    header_name = Path(header_name)

    try:
        relative = header_name.relative_to(srcdir)
    except ValueError:
        relative = header_name

    relative = relative.as_posix()

    return xml_index.get(relative, [])


def parse_doxygen_config(filename):
    """Read doxygen config and save it into a python dictionnary

    Parameters
    ----------
    filename : string or Path()
       full path to doxygen file

    Returns a python dictionnary
    """
    result = {}
    with open(filename) as ff:
        # remove comment lines
        conf = [
            n.strip()
            for n in ff.readlines()
            if (not n.startswith("#") and not n.startswith("\n"))
        ]
        for d in conf:
            if d.count("=") > 0:
                res = d.split("=")
                result[res[0].rsplit()[0]] = res[1]
                backup = res.copy()
            else:
                result[backup[0].rsplit()[0]] += d
    return result


def filter_dot_in_xml_formulas(xmlfile):
    """Replace \\dot with \dot in xml input.

    dot is confusing for doxygen (may be latex or graphviz),
    so in latex formula inside \rst
    we need to use \\dot and replace it later,
    when breathe/sphinx comes into action.

    Parameters
    ----------
    xmlfile: Path()
        xml file name (full path) (in-out param)
    """
    fileout = xmlfile.stem + ".tmp"
    with open(xmlfile, "r+", encoding="utf8") as f:
        lines = f.read()
    newlines = lines.replace(r"\\dot", r"\dot")
    with open(fileout, "w", encoding="utf8") as f:
        f.write(newlines)
    shutil.move(fileout, xmlfile)


def replace_uppercase_letters(filename):
    """Replace uppercase letters in a string
    with _lowercase (following doxygen way)

    e.g. : TimeStepping --> _time_stepping

    This is useful to postprocess filenames from xml-doxygen outputs

    Usage:

    result = replace_uppercase_letters(input)
    """
    r = []
    for c in filename:
        # l being: last character was not uppercase
        newc = c
        if c.isupper():
            newc = "_" + c.lower()
        r.append(newc)
    return "".join(r)


def get_xml_compound_infos(compound):
    """Returns object (class, struct ...) name, kind
    and brief description
    from an xml node (compound)
    """
    kind = compound.attrib["kind"]
    names = compound.findall("compoundname")
    descr = compound.findall("briefdescription")
    assert len(names) == 1
    assert len(descr) == 1
    # res = ''
    content = descr[0].find("para")
    if content is not None:
        res = ET.tostring(content, method="text")
        res = "\n    ".join(res.decode().split("\n"))
        res = find_and_replace_math(res)
    else:
        res = ""
    return names[0].text, kind, res


def find_and_replace_math(content):
    """Replace latex-like math formulas in content
    with sphinx-like math formulas

    content : a string.
    """
    if content.count("$") > 1:
        start = content.find("$")
        end = content.find("$", start + 1)
        doxy_latex = content[start : end + 1]
        rst_latex = r":math:`" + doxy_latex[1:-1].strip() + r"`"
        content = content.replace(doxy_latex, rst_latex)
    return content


def replace_latex(inoutfile, latex_sources):
    """Post processing of latex forms in docstrings.

    Parameters
    ----------

    inoutfile : Path()
       name (full path) of the python file to process
    latex_sources : string or Path()
       directory which contains pickle files with latex forms
       (result of do_latex or do_verbatim calls)

    Usually : inoutfile = some_component.py (e.g. numerics.py)
    and latex_dir = wrap/siconos/tmp_component_name.

    This function is supposed to be called by a target
    generated with cmake (make <component>_replace_latex)

    It is also called  by module_docstrings2rst.
    """
    latex_sources = Path(latex_sources).resolve()

    # Parse latex_sources and get all pickle files
    formfiles = [f for f in latex_sources.glob("latex_*.pickle")]

    # Runner : use sed rather than python replace. But less portable (?)
    # runner = os.path.join(os.path.dirname(os.path.abspath(__file__)),
    #                      'replace_latex.sh')

    # temp file for outputs.
    inoutfile = Path(inoutfile)
    target = Path(inoutfile.parent, inoutfile.stem + ".copy").resolve()
    shutil.copyfile(inoutfile, target)
    # Read input (.py)
    with open(inoutfile, "r") as f:
        source_lines = f.readlines()
    rst = []
    # Parse and replace :
    # for each formula found in each pickle file,
    # replace FORMULA_Id with the proper string
    # in temp list.
    for fname in formfiles:
        with open(fname, "rb") as f:
            latex_dict = pickle.load(f)
            for form in latex_dict:
                idf = "FORMULA" + str(form) + "_"
                # we must \\dot in \rst doxygen
                # else there is a confusion with dot from graphviz.
                formula = latex_dict[form]["latex"].replace(r"\\", "\\\\")
                # escape \
                formula = latex_dict[form]["latex"].replace("\\", "\\\\")
                formula_type = latex_dict[form]["label"]  # inline or not
                # formula = ''.join(formula)
                for line in source_lines:
                    if formula_type == "inline":
                        rst.append(line.replace(idf, formula))
                    else:
                        indent = len(line) - len(line.lstrip())
                        rst.append(
                            line.replace(idf, textwrap.indent(formula, indent * " "))
                        )
                source_lines = list(rst)
                rst = []

    # Replace .py with new results.
    with open(target, "w") as f:
        for line in source_lines:
            f.write(line)
    shutil.move(target, inoutfile)
