"""Tools used during configuration and build process of
Siconos documentation.

This modules contains functions dedicated to the generation
of rst files from xml output generated by doxygen,
from c++ inline documentation.

Process :
hpp (C++) --> doxygen --> xml

xml --> this --> rst files in a 'breathe' complient format.


Siconos is a program dedicated to modeling, simulation and control
 of non smooth dynamical systems.

 Copyright 2024 INRIA.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""

import os
import textwrap
import re
import buildtools as bt
from pathlib import Path
from gendoctools import common

try:
    import lxml.etree as ET
except ImportError:
    import xml.etree.ElementTree as ET

components_docs = {
    "externals": "API or tools related to external software libraries used by Siconos.",
    "numerics": "a collection of low-level algorithms for solving basic algebra and"
    " optimization problem arising in the simulation of nonsmooth dynamical systems.",
    "kernel": "high-level API to modelise and simulate nonsmooth dynamical systems.",
    "control": "control toolbox",
    "mechanics": "toolbox for collision detection and joints",
    "mechanisms": "toolbox for collision detection and joints"
    " (legacy version, won’t be sustained in long term)",
    "io": "tools related to input/outputs (hdf5, vtk …)",
}


def create_breathe_files(headers, srcdir, component_name, sphinx_directory, xml_output):
    """Create rst files for sphinx from xml (doxygen) outputs generated
       from headers.

    Parameters
    ----------
    headers : list
        Header files to parse.
    srcdir : str
        Absolute path to C/C++ sources
    component_name : str
        component (numerics, kernel, ...) of interest
    sphinx_directory : str
        Root sphinx directory.
    xml_output : str
        (full) path to the requested xml outputs

    Notes:
    * for each header, rst files (class, struct, file and source codes)
      will be generated
    * three other 'main' rst files will be produced :
       * breathe_api.rst, with the toctree for all classes and structs
       * files_list.rst, with the toctree for all files documentation
       * sources_list.rst with the toctree for all program listings

    This function is supposed to be called by a target created with cmake
    (make <component>-xml2rst)

    """
    # Get all headers for the current component, as a list.
    headers = bt.parse_cmake_list(headers)

    sphinx_directory = Path(
        sphinx_directory,
        "reference",
        "cpp",
        component_name,
    )

    sphinx_directory.mkdir(parents=True, exist_ok=True)

    # Get xml files path
    xmlconf = {}
    xmlconf["XML_OUTPUT"] = Path(xml_output)

    # Build Doxygen XML index once
    xml_index = common.build_doxygen_xml_index(
        xmlconf["XML_OUTPUT"],
        Path(srcdir),
    )

    all_index = {}

    # -- Create rst for classes, structs and files found in xml directory --
    for hfile in headers:

        xml2rst(
            Path(hfile),
            srcdir,
            component_name,
            sphinx_directory,
            xmlconf,
            all_index,
            xml_index,
        )

    # -- Create rst files to collect list of classes and files
    # (i.e. files created above) --
    class_and_struct_files = [
        f for f in sphinx_directory.glob("*.rst") if f.stem in all_index
    ]
    class_and_struct_files.sort()
    pgm_files = sorted(sphinx_directory.glob("pgm_*.rst"))
    rst_files = sorted(sphinx_directory.glob("file_*.rst"))
    all_files = class_and_struct_files + rst_files
    all_files.sort()

    # -- Name of the main rst files for the current component --
    # usually : docs/sphinx/reference/cpp/component_name/autodoc_all.rst
    outputname = Path(sphinx_directory, "autodoc_all.rst")
    autodoc_collect(
        outputname,
        all_files,
        all_index,
        component_name,
    )
    # Classes and structs
    outputname = Path(sphinx_directory, "autodoc_classes.rst")
    autodoc_collect(
        outputname,
        class_and_struct_files,
        all_index,
        component_name,
        subtitle="Classes and structs",
    )

    # Files doc
    outputname = Path(sphinx_directory, "autodoc_files.rst")
    autodoc_collect(
        outputname,
        rst_files,
        all_index,
        component_name,
        subtitle="Files documentation",
    )
    # Programs listings
    autodoc_collect_pgm(
        pgm_files,
        component_name,
        sphinx_directory,
    )


def xml2rst(
    headername,
    srcdir,
    component_name,
    sphinx_directory,
    doxyconf,
    all_index,
    xml_index,
):
    """Generate rst file(s) from xml (doxygen outputs) for given C/C++ header.

    Parameters
    ----------
    headername : Path()
        Name of the header (full path).
    srcdir : string
        Absolute path to c/c++ sources (CMAKE_SOURCE_DIR).
    component_name : string
        Component (numerics, kernel, ...) of interest
        (i.e. breathe project).
    sphinx_directory : Path()
        Directory where rst files will be written.
    doxyconf : dict
        Dict describing xml/doxy configuration.
    all_index : dict
        Mapping (roughly xml/rst) used later to build the API index.
    xml_index : dict
        global index from doxygen (generated in create_breathe...)
    """
    # First get list of xml files generated from current header by doxygen
    xml_files = common.get_xml_files(
        headername,
        xml_index,
        Path(srcdir),
    )
    # Then, for each xml, write sphinx header.
    for xmlfile in xml_files:
        common.filter_dot_in_xml_formulas(xmlfile)
        root = ET.parse(xmlfile).getroot()
        compound = root.find("compounddef")
        if compound is None:
            continue
        name, kind, descr = common.get_xml_compound_infos(compound)
        refid = compound.attrib["id"]
        # Classes and structs
        if kind in ("class", "struct"):
            all_index[refid] = (name, descr.strip())
            label = ".. _{}:\n\n".format(refid)
            title = "{} {}\n".format(
                kind.title(),
                name,
            )
            title += len(title) * "-" + "\n\n"
            gen = label + title
            gen += ".. doxygen{}:: {}\n".format(kind, name)
            gen += "   :project: {}\n".format(component_name)
            gen += "   :members:\n\n"
            outputname = Path(
                sphinx_directory,
                refid + ".rst",
            )

        # Header files
        elif kind == "file":
            shortname = name
            refname = sphinxref4headername(
                headername.as_posix(),
                srcdir,
            )
            label = ".. _file{}:\n\n".format(refname)
            title = "File {}\n".format(shortname)
            title += len(title) * "-" + "\n\n"
            gen = label + title
            gen += ".. doxygenfile:: {}\n".format(shortname)
            gen += "   :project: {}\n\n".format(component_name)
            outputname = Path(
                sphinx_directory,
                "file_" + headername.name.replace(".", "_") + ".rst",
            )
            all_index[headername.name] = descr
        else:
            continue

        with open(outputname, "wt") as out:
            out.write(gen)

    # Program listing
    create_rst_for_program(
        headername.as_posix(),
        srcdir,
        sphinx_directory,
        True,
    )


def create_rst_for_program(headername, srcdir, sphinx_directory, filterdox=False):
    """Build rst file from header (c++), for a 'pgm' target in sphinx.


    Parameters
    ----------
    headername : string
        name of the header (full path)
    srcdir : string
        absolute path to c/c++ sources (CMAKE_SOURCE_DIR)
    sphinx_directory : Path()
        directory where rst files will be written
    filterdox : boolean
        true to remove doxygen comments from program listings in sphinx
    """
    shortname = headername.split(srcdir)[-1][1:]
    shortname = shortname.replace(r"./", "")
    outputname = "pgm_" + shortname.replace("/", "_").replace(".", "_")
    outputname = Path(sphinx_directory, outputname + ".rst")
    refname = sphinxref4headername(headername, srcdir)
    title = "Program listing for file " + shortname
    label = ".. _pgm" + refname + ":\n\n"
    lenname = len(title)
    title = label + title + "\n" + lenname * "=" + "\n\n"
    doc = "* Return to documentation for :ref:`this file<file"
    doc += refname + ">`\n\n"
    gen = title + doc
    if filterdox:
        d = filter_comments(headername)
    else:
        with open(headername, "r") as f:
            d = f.read()
    gen += ".. code-block:: c++\n"
    gen += "    :linenos:\n\n"
    text = textwrap.indent(d, 4 * " ")
    gen += text

    with open(outputname, "wt") as out:
        out.write(gen)


def autodoc_collect(outputname, files_list, all_index, component_name, subtitle=None):
    """Create a rst file, autodoc-like, used as table of contents
    either for classes, structs or files (depends on outputname and subtitle)

    Parameters
    ----------
    files_list : list of rst files to take into account
    all_index : dict
        mapping between class names and descriptions (output from xml2rst)
    component_name : string
        current component name
    subtitle : string, optional
        text header for rst file
    """

    if subtitle:
        subtitle += "\n"
        subtitle += len(subtitle) * "-"
        subtitle += "\n\n"
    else:
        subtitle = ""

    with open(outputname, "wt") as out:
        # For each file in the list,
        # create a breathe entry in outputname
        out.write(subtitle)
        for f in sorted(files_list):
            rst_id = f.stem
            # classes / structs
            if rst_id in all_index:
                cppname, descr = all_index[rst_id]
                out.write(
                    "* :doc:`{} <{}>`".format(
                        cppname,
                        rst_id,
                    )
                )
                if descr:
                    out.write(" : " + descr)
                out.write("\n")

            # files
            elif rst_id.startswith("file_"):
                shortname = rst_id[len("file_") :].replace("_", ".")
                out.write(
                    "* :doc:`{} <{}>`\n".format(
                        shortname,
                        rst_id,
                    )
                )


def autodoc_collect_pgm(pgm_files, component_name, sphinx_directory):
    """Create a rst file that list all headers of the current component
    --> table of contents 'files documentation' in html outputs.
    Parameters
    ----------
    pgm_files : list of rst files to take into account
    component_name : string
        current component name
    sphinx_directory : Path
        sphinx root dir (binary)
    """
    outputname = Path(sphinx_directory, "autodoc_pgm.rst")
    basename = "/reference/cpp/" + component_name + "/"
    sphinx_directory = sphinx_directory.as_posix()
    label = ".. _" + component_name + "_pgm_listings:\n\n"
    title = component_name.title() + " programs listings\n"
    title += len(title) * "-" + "\n\n"
    title = label + title
    with open(outputname, "wt") as out:
        out.write(title)
        out.write(".. toctree::\n    :maxdepth: 2\n\n")
        for f in pgm_files:
            name = f.stem
            # Transforms rst file name into header name ...
            splits = name.split("_")
            shorttitle = "/".join(splits[2:-1]) + "." + splits[-1]
            name = basename + name
            gen = textwrap.indent(shorttitle + "<" + name + ">\n", 4 * " ")
            out.write(gen)


def sphinxref4headername(headername, srcdir):
    """Returns the reference to set in sphinx for a given file name

    Parameters
    ----------
    headername : string
        name of the input file (full path)
    srcdir : part of the name to remove from ref (usually CMAKE_SOURCE_DIR)

    """
    if srcdir:
        refname = headername.split(srcdir)[-1]
    else:
        refname = headername
    refname = refname.replace("/", "_")
    return refname


def filter_comments(headername):
    """Returns list of lines from a
    source file, without doxygen comments.
    """

    def replacer(match):
        s = match.group(0)
        if s.startswith("/"):
            return " "  # note: a space and not an empty string
        return s

    with open(headername, "r") as f:
        text = f.read()
        pattern = re.compile(
            r'//.*?$|/\*.*?\*/|\'(?:\\.|[^\\\'])*\'|"(?:\\.|[^\\"])*"',
            re.DOTALL | re.MULTILINE,
        )
        return re.sub(pattern, replacer, text)


def build_cpp_api_main(outputdir, components):
    """Parse existing autodoc_...rst files generated for C++ API
    and collect them into  main_autodoc.rst
    in sphinx/reference/cpp/component directory
    (one for each component)

    Call: make rst_api

    Parameters
    ----------
    outputdir : Path()
         sphinx directory which contains rst files
         generated for the api
    components : list
         list of active siconos components
    """

    mainrst_filename = Path(outputdir, "cpp_api.rst")
    # list documented (cpp) packages
    docpp_dir = Path(outputdir, "cpp")
    packages = [f for f in docpp_dir.glob("*")]
    packages = [p.name for p in packages if os.listdir(p)]
    # trick to print components in the expected order.
    packages = [p for p in components if p in packages]
    # indent = 4 * " "

    # with open(mainrst_filename, "w") as f:
    #     # label = '.. _siconos_cpp_reference:\n\n\n'
    #     f.write(".. _cpp_api:\n\n")
    #     title = "Siconos C/C++ API reference"
    #     title += "\n" + len(title) * "=" + "\n\n"
    #     title += "This is the documentation of C/C++ interface to Siconos.\n\n\n"
    #     # f.write(label)
    #     f.write(title)
    #     header = ".. toctree::\n    :maxdepth:2\n\n"
    #     f.write(header)

    #     class_diag = "Class diagrams (UML view)"
    #     class_diag += " </reference/class_diagrams>\n"
    #     class_diag = textwrap.indent(class_diag, "    ")
    #     f.write(class_diag)
    #     for p in packages:
    #         # Create main autodoc file for the current component
    #         write_cpp_component_autodoc(p, docpp_dir)
    #         # And add it to the current toc
    #         title = p.title() + ": " + components_docs[p]
    #         directive = title + " <cpp/" + p + "/main_autodoc>\n"
    #         directive = textwrap.indent(directive, "    ")
    #         f.write(directive)
    #     f.write("\n")

    with open(mainrst_filename, "w") as f:
        f.write(".. _cpp_api:\n\n")
        title = "Siconos C/C++ API reference"
        title += "\n" + len(title) * "=" + "\n\n"
        title += "This is the documentation of C/C++ interface to Siconos.\n\n\n"
        f.write(title)
        # Grid of cards
        f.write(".. grid:: 3\n")
        f.write("   :gutter: 3\n\n")

        # Class diagrams
        f.write("   .. grid-item-card:: Class diagrams\n")
        f.write("      :link: /reference/class_diagrams\n")
        f.write("      :class-card: sd-bg-code\n")
        f.write("      :link-type: doc\n\n")
        f.write("      Class diagrams (UML view).\n\n")

        # Components
        for p in packages:
            # Generate component documentation
            write_cpp_component_autodoc(p, docpp_dir)
            f.write(f"   .. grid-item-card:: {p.title()}\n")
            f.write(f"      :link: cpp/{p}/main_autodoc\n")
            f.write("      :class-card: sd-bg-code\n")
            f.write("      :link-type: doc\n\n")
            f.write(f"      {components_docs[p]}\n\n")

        # Hidden toctree (navigation only)
        #
        f.write(".. toctree::\n")
        f.write("   :hidden:\n")
        f.write("   :maxdepth: 2\n\n")
        f.write("   /reference/class_diagrams\n")
        for p in packages:
            f.write(f"   cpp/{p}/main_autodoc\n")


def write_cpp_component_autodoc(component, sphinx_directory):
    """Write main autodoc file for current component"""
    outputname = Path(sphinx_directory, component, "main_autodoc.rst")
    with open(outputname, "wt") as f:
        title = component.title() + " component C/C++ API documentation\n"
        title += len(title) * "=" + "\n\n"
        ppath = "/reference/cpp/" + component
        f.write(title)
        pgm_listings = "Check :ref:`" + component + "_pgm_listings`"
        pgm_listings += " for a complete list of headers for this component."
        f.write(pgm_listings + "\n\n")
        directive = ".. include:: " + ppath + "/autodoc_classes.rst\n\n"
        directive += ".. include:: " + ppath + "/autodoc_files.rst\n"
        indent = ""
        f.write(textwrap.indent(directive, indent))
        f.write("\n")
