"""Tools used during configuration and build process of
Siconos documentation.

This modules contains functions dedicated to the generation
of rst files from xml output generated by doxygen,
from python docstrings.

It also includes tools to create docstrings in swig
from c++ headers, that will be inserted in generated python code.

Process :
hpp (C++) --> doxygen --> xml --> rst


Siconos is a program dedicated to modeling, simulation and control
 of non smooth dynamical systems.

 Copyright 2024 INRIA.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""

import textwrap
from pathlib import Path
import operator


modules_docs = {
    "siconos_externals": "API or tools related to external software libraries used by Siconos.",
    "siconos_numerics": "a collection of low-level algorithms for solving basic algebra and optimization problem arising in the simulation of nonsmooth dynamical systems.",
    "siconos_kernel": "high-level API to modelise and simulate nonsmooth dynamical systems.",
    "siconos_control": "control toolbox",
    "siconos_mechanics": "toolbox for collision detection and joints",
    "siconos_mechanisms": "toolbox for collision detection and joints (legacy version, won’t be sustained in long term)",
    "siconos_io": "tools related to input/outputs (hdf5, vtk …)",
}


def build_python_api_main(outputdir, components):
    """Parse existing rst files (one for each class,
    + those for functions) generated for python API
    and collect them into  python_api.rst
    in sphinx/reference directory.

    Call: make rst_api

    Parameters
    ----------
    outputdir : Path()
         sphinx directory which contains rst files
         generated for the api
    components : list
         list of active siconos python modules
    """
    mainrst_filename = Path(outputdir, "index.rst")
    # list documented (python) packages
    docpython_dir = Path(outputdir, "python")
    packages = [f for f in docpython_dir.glob("*")]
    packages = [p.name for p in packages]
    # (ugly) trick to print components in the expected order.
    pack = {}
    for p in components:
        for pname in packages:
            if pname.count(p) > 0:
                pack[pname] = components[p]
    packages = [p[0] for p in sorted(pack.items(), key=operator.itemgetter(1))]

    if len(packages) > 0:
        with open(mainrst_filename, "a") as f:
            # label = '.. _siconos_python_reference:\n\n\n'
            title = "Siconos Python API reference"
            title += "\n" + len(title) * "#" + "\n\n"
            title += "This is the documentation of "
            title += "`python <https://www.python.org/>`_ "
            title += "interface to Siconos.\n\n\n"
            header = ".. toctree::\n    :maxdepth:3\n\n"
            f.write(title)
            f.write(header)
            for p in packages:
                if p in modules_docs:
                    title = p.replace("_", ".") + ": " + modules_docs[p]
                    directive = title + " <python/" + p + "/autodoc>\n"
                else:
                    directive = "python/" + p + "/autodoc\n\n"
                directive = textwrap.indent(directive, "    ")
                f.write(directive)
            f.write("\n")
