#ifndef FRICTION_CST_H
#define FRICTION_CST_H

enum FRICTION_SOLVER
{
  SICONOS_FRICTION_2D_NSGS = 400,
  SICONOS_FRICTION_2D_NLGS = 401,
  SICONOS_FRICTION_2D_PGS = 402,
  SICONOS_FRICTION_2D_CPG = 403,
  SICONOS_FRICTION_2D_LATIN = 404,
  SICONOS_FRICTION_3D_NSGS = 500,
  SICONOS_FRICTION_3D_NSGSV = 501,
  SICONOS_FRICTION_3D_PROX = 502,
  SICONOS_FRICTION_3D_TFP = 503,
  SICONOS_FRICTION_3D_GLOBALAC = 504,
  SICONOS_FRICTION_3D_DSFP = 505,
  SICONOS_FRICTION_3D_NCPGlockerFBFixedPoint = 506,
  SICONOS_FRICTION_3D_AlartCurnierNewton = 507,
  SICONOS_FRICTION_3D_NCPGlockerFBNewton = 508,
  SICONOS_FRICTION_3D_ProjectionOnConeWithDiagonalization = 509,
  SICONOS_FRICTION_3D_ProjectionOnCone = 510,
  SICONOS_FRICTION_3D_ProjectionOnConeWithLocalIteration = 511,
  SICONOS_FRICTION_3D_projectionOnConeWithRegularization = 512,
  SICONOS_FRICTION_3D_NCPGlockerFBPATH = 513,
  SICONOS_FRICTION_3D_projectionOnCylinder = 514,
  SICONOS_FRICTION_3D_ProjectionOnCone_velocity = 515,
  SICONOS_FRICTION_3D_PGoC = 516,
  SICONOS_FRICTION_3D_DeSaxceFixedPoint = 517,
  SICONOS_FRICTION_3D_DampedAlartCurnierNewton = 518,
  SICONOS_FRICTION_3D_PRIMAL_NSGS_WR = 600,
  SICONOS_FRICTION_3D_PRIMAL_NSGSV_WR = 601,
  SICONOS_FRICTION_3D_PRIMAL_PROX_WR = 602,
  SICONOS_FRICTION_3D_PRIMAL_DSFP_WR = 603,
  SICONOS_FRICTION_3D_PRIMAL_TFP_WR = 604,
  SICONOS_FRICTION_3D_PRIMAL_NSGS = 605,
  SICONOS_FRICTION_3D_PRIMAL_GLOBALAC_WR = 606
};



extern char  SICONOS_FRICTION_2D_NSGS_STR [];
extern char  SICONOS_FRICTION_2D_NLGS_STR [];
extern char  SICONOS_FRICTION_2D_PGS_STR [];
extern char  SICONOS_FRICTION_2D_CPG_STR [];
extern char  SICONOS_FRICTION_2D_LATIN_STR [];
extern char  SICONOS_FRICTION_3D_NSGS_STR [];
extern char  SICONOS_FRICTION_3D_NSGSV_STR [];
extern char SICONOS_FRICTION_3D_PROX_STR[];
extern char  SICONOS_FRICTION_3D_TFP_STR [];
extern char  SICONOS_FRICTION_3D_GLOBALAC_STR [];
extern char  SICONOS_FRICTION_3D_DSFP_STR[] ;
extern char SICONOS_FRICTION_3D_NCPGlockerFBFixedPoint_STR[];
extern char SICONOS_FRICTION_3D_AlartCurnierNewton_STR[];
extern char SICONOS_FRICTION_3D_DampedAlartCurnierNewton_STR[];
extern char  SICONOS_FRICTION_3D_NCPGlockerFBNewton_STR[];
extern char SICONOS_FRICTION_3D_ProjectionOnConeWithDiagonalization_STR[];
extern char SICONOS_FRICTION_3D_ProjectionOnCone_STR[];
extern char SICONOS_FRICTION_3D_ProjectionOnConeWithLocalIteration_STR[];
extern char SICONOS_FRICTION_3D_projectionOnConeWithRegularization_STR[];
extern char SICONOS_FRICTION_3D_NCPGlockerFBPATH_STR[];
extern char SICONOS_FRICTION_3D_projectionOnCylinder_STR[];
extern char SICONOS_FRICTION_3D_ProjectionOnCone_velocity_STR[];
extern char SICONOS_FRICTION_3D_PGoC_STR[];
extern char SICONOS_FRICTION_3D_DeSaxceFixedPoint_STR[];
extern char SICONOS_FRICTION_3D_PRIMAL_NSGS_WR_STR [];
extern char SICONOS_FRICTION_3D_PRIMAL_NSGSV_WR_STR [];
extern char SICONOS_FRICTION_3D_PRIMAL_PROX_WR_STR [];
extern char SICONOS_FRICTION_3D_PRIMAL_DSFP_WR_STR [];
extern char SICONOS_FRICTION_3D_PRIMAL_TFP_WR_STR [];
extern char SICONOS_FRICTION_3D_PRIMAL_NSGS_STR [];
extern char SICONOS_FRICTION_3D_PRIMAL_GLOBALAC_WR_STR [];





#endif
