#ifndef MLCP_CST_H
#define MLCP_CST_H

enum MLCP_SOLVER
{
  SICONOS_MLCP_PGS = 100,
  SICONOS_MLCP_RPGS = 101,
  SICONOS_MLCP_PSOR = 102,
  SICONOS_MLCP_RPSOR = 103,
  SICONOS_MLCP_PATH = 104,
  SICONOS_MLCP_ENUM = 105,
  SICONOS_MLCP_SIMPLEX = 106,
  SICONOS_MLCP_DIRECT_ENUM = 107,
  SICONOS_MLCP_PATH_ENUM = 108,
  SICONOS_MLCP_DIRECT_SIMPLEX = 109,
  SICONOS_MLCP_DIRECT_PATH = 110,
  SICONOS_MLCP_DIRECT_PATH_ENUM = 111,
  SICONOS_MLCP_FB = 112,
  SICONOS_MLCP_DIRECT_FB = 113
};

extern char  SICONOS_NONAME_STR[] ;
extern char  SICONOS_MLCP_PGS_STR[] ;
extern char  SICONOS_MLCP_RPGS_STR[] ;
extern char  SICONOS_MLCP_PSOR_STR[];
extern char  SICONOS_MLCP_RPSOR_STR[];
extern char  SICONOS_MLCP_PATH_STR[];
extern char  SICONOS_MLCP_ENUM_STR[];
extern char  SICONOS_MLCP_SIMPLEX_STR[];
extern char  SICONOS_MLCP_DIRECT_ENUM_STR[];
extern char  SICONOS_MLCP_PATH_ENUM_STR[];
extern char  SICONOS_MLCP_DIRECT_SIMPLEX_STR[];
extern char  SICONOS_MLCP_DIRECT_PATH_STR [];
extern char  SICONOS_MLCP_DIRECT_PATH_ENUM_STR[];
extern char  SICONOS_MLCP_FB_STR[];
extern char  SICONOS_MLCP_DIRECT_FB_STR[];

#endif
