# Find MUMPS includes and libraries.
# The following variables are set if MUMPS is found.  If MUMPS is not
# found, MUMPS_FOUND is set to false.
#  MUMPS_FOUND        - True when the MUMPS include directory is found.
#  MUMPS_INCLUDE_DIRS - the path to where the Siconos MUMPS include files are.
#  MUMPS_LIBRARY_DIRS - The path to where the Siconos library files are.
#  MUMPS_LIBRARIES    - The libraries to link against Siconos MUMPS

# One may want to use a specific MUMPS Library by setting
# MUMPS_LIBRARY_DIRECTORY before FIND_PACKAGE(MUMPS)

IF(MUMPS_LIBRARY_DIRECTORY)
  FIND_LIBRARY(MUMPS_FOUND dmumps PATHS "${MUMPS_LIBRARY_DIRECTORY}")
ELSE(MUMPS_LIBRARY_DIRECTORY)
  FIND_LIBRARY(MUMPS_FOUND dmumps)
ENDIF(MUMPS_LIBRARY_DIRECTORY)

IF(MUMPS_LIBRARY_DIRECTORY)
  FIND_LIBRARY(MUMPS_COMMON_FOUND mumps_common PATHS "${MUMPS_LIBRARY_DIRECTORY}")
ELSE(MUMPS_LIBRARY_DIRECTORY)
  FIND_LIBRARY(MUMPS_COMMON_FOUND mumps_common)
ENDIF(MUMPS_LIBRARY_DIRECTORY)

IF(MUMPS_LIBRARY_DIRECTORY)
  FIND_LIBRARY(METIS_FOUND metis PATHS "${MUMPS_LIBRARY_DIRECTORY}")
ELSE(MUMPS_LIBRARY_DIRECTORY)
  FIND_LIBRARY(METIS_FOUND metis)
ENDIF(MUMPS_LIBRARY_DIRECTORY)

IF(MUMPS_FOUND)
  GET_FILENAME_COMPONENT(MUMPS_LIBRARY_DIRS ${MUMPS_FOUND} PATH)
  SET(MUMPS_LIBRARIES ${MUMPS_FOUND} ${MUMPS_COMMON_FOUND} ${METIS_FOUND})
  GET_FILENAME_COMPONENT(MUMPS_LIBRARY_DIRS_DIR ${MUMPS_LIBRARY_DIRS} PATH)
  SET(MUMPS_INCLUDE_DIRS ${MUMPS_LIBRARY_DIRS_DIR}/include)
ELSE(MUMPS_FOUND)
  IF(MUMPS_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR
      "Required MUMPS library not found. Please specify library location in MUMPS_LIBRARY_DIRECTORY")
  ENDIF(MUMPS_FIND_REQUIRED)
ENDIF(MUMPS_FOUND)
