SET(PIPOL_IMAGE $ENV{PIPOL_IMAGE})  
SET(_STMP "[${PIPOL_IMAGE}]")
IF(_STMP STREQUAL "[]")
ELSE(_STMP STREQUAL "[]")
  # pipol<n> 
  SET(SITE "PIPOL")
  SET(BUILDNAME "${BUILDNAME} ${PIPOL_IMAGE}")
ENDIF(_STMP STREQUAL "[]")
