SET(PIPOL_IMAGE $ENV{PIPOL_IMAGE})  
SET(_STMP "[${PIPOL_IMAGE}]")
IF(_STMP STREQUAL "[]")
ELSE(_STMP STREQUAL "[]")
  # pipol<n> 
  GET_FILENAME_COMPONENT(_IMAGE_NAME ${PIPOL_IMAGE} NAME_WE)
  SET(SITE "PIPOL")
  SET(BUILDNAME "${BUILDNAME} ${_IMAGE_NAME}")
ENDIF(_STMP STREQUAL "[]")
