#
# Siconos documentation with Doxygen 
#

# Style sheet
FILE(GLOB CSS_FILES config/css/*.* config/css/*)
FOREACH(FILE ${CSS_FILES})
  IF(NOT IS_DIRECTORY ${FILE})
    FILE(RELATIVE_PATH RFILE ${CMAKE_SOURCE_DIR} ${FILE})
    CONFIGURE_FILE(${FILE} ${CMAKE_BINARY_DIR}/${RFILE} COPYONLY)
  ENDIF(NOT IS_DIRECTORY ${FILE})
ENDFOREACH(FILE ${CSS_FILES})

# build in Generated DOCS
IF (NOT DOXYGEN_OUTPUT)
  SET(DOXYGEN_OUTPUT ${CMAKE_BINARY_DIR}/../GeneratedDocs)
ENDIF(NOT DOXYGEN_OUTPUT)

FILE(MAKE_DIRECTORY ${DOXYGEN_OUTPUT})
FILE(MAKE_DIRECTORY ${DOXYGEN_OUTPUT}/${PROJECT})
FILE(MAKE_DIRECTORY ${DOXYGEN_OUTPUT}/Tags)


INCLUDE(TargetDoc OPTIONAL)
