#ifndef RELAY_CST_H
#define RELAY_CST_H

enum RELAY_SOLVER
{
  SICONOS_RELAY_PGS = 300,
  SICONOS_RELAY_ENUM = 301,
  SICONOS_RELAY_PATH = 302,
  SICONOS_RELAY_LEMKE = 303,
  SICONOS_RELAY_LATIN = 304,
  SICONOS_RELAY_NLGS = 305

};




extern char  SICONOS_RELAY_PGS_STR[];
extern char  SICONOS_RELAY_PATH_STR[];
extern char  SICONOS_RELAY_ENUM_STR[];
extern char  SICONOS_RELAY_NLGS_STR[];
extern char  SICONOS_RELAY_LEMKE_STR[];
extern char  SICONOS_RELAY_LATIN_STR[];
#endif
