/* g2c.h  --  g77 version of f2c (Standard Fortran to C header file) */

/* This file is generated by the g77 libg2c configuration process from a
   file named g2c.hin.  This process sets up the appropriate types,
   defines the appropriate macros, and so on.  The resulting g2c.h file
   is used to build g77's copy of libf2c, named libg2c, and also can
   be used when compiling C code produced by f2c to link the resulting
   object file(s) with those produced by the same version of g77 that
   produced this file, allowing inter-operability of f2c-compiled and
   g77-compiled code.  */

/**  barf  [ba:rf]  2.  "He suggested using FORTRAN, and everybody barfed."

  - From The Shogakukan DICTIONARY OF NEW ENGLISH (Second edition) */

#ifndef G2C_COMPATGCC4
#define G2C_COMPATGCC4

typedef long int integer;
typedef double doublereal;
typedef struct
{
  doublereal r, i;
} doublecomplex;

#endif
