SET(WithQGLViewer TRUE)

FIND_PACKAGE(SiconosMechanics REQUIRED)
FIND_PACKAGE(Bullet REQUIRED)
INCLUDE_DIRECTORIES(${SiconosMechanics_INCLUDE_DIRS})
INCLUDE_DIRECTORIES(${BULLET_INCLUDE_DIRS})	
LINK_DIRECTORIES(${SiconosMechanics_LIBRARY_DIRS})
LIST(APPEND LINKER_LIBRARIES ${SiconosMechanics_LIBRARIES} ${BULLET_LIBRARIES} )
