#ifndef LCP_CST_H
#define LCP_CST_H

enum LCP_SOLVER
{
  SICONOS_LCP_LEMKE = 200,
  SICONOS_LCP_NSGS_SBM = 201,
  SICONOS_LCP_PGS = 202,
  SICONOS_LCP_CPG = 203,
  SICONOS_LCP_LATIN = 204,
  SICONOS_LCP_LATIN_W = 205,
  SICONOS_LCP_QP = 206,
  SICONOS_LCP_NSQP = 207,
  SICONOS_LCP_NEWTONMIN = 208,
  SICONOS_LCP_NEWTONFB = 209,
  SICONOS_LCP_PSOR = 210,
  SICONOS_LCP_RPGS = 211,
  SICONOS_LCP_PATH = 212,
  SICONOS_LCP_ENUM = 213
};



extern char *  SICONOS_LCP_LEMKE_STR;
extern char *  SICONOS_LCP_NSGS_SBM_STR;
extern char *  SICONOS_LCP_PGS_STR;
extern char *  SICONOS_LCP_CPG_STR;
extern char *  SICONOS_LCP_LATIN_STR;
extern char *  SICONOS_LCP_LATIN_W_STR;
extern char *  SICONOS_LCP_QP_STR;
extern char *  SICONOS_LCP_NSQP_STR;
extern char *  SICONOS_LCP_NEWTONMIN_STR;
extern char *  SICONOS_LCP_NEWTONFB_STR;
extern char *  SICONOS_LCP_PSOR_STR;
extern char *  SICONOS_LCP_RPGS_STR;
extern char *  SICONOS_LCP_PATH_STR;
extern char *  SICONOS_LCP_ENUM_STR;

#endif
