"""
Tools used during configuration and build process
(most of them used in CMake files, during build or runtime).

This file is to be copied into CMAKE_BINARY_DIR/share using configure_file

 Siconos is a program dedicated to modeling, simulation and control
 of non smooth dynamical systems.

 Copyright 2025 INRIA.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""

import textwrap
import os


def parse_cmake_list(var):
    """Transform cmake list-like variables
    into python lists.

    Parameters
    ----------
    var : string
        like "a;b;c"

    Returns python list

    If var is already a list, does nothing.

    Example::

        a = parse_cmake_list("var1;var2;var3;")
        # --> a = ['var', 'var2', 'var3']

    """
    if isinstance(var, list):
        return var
    if var != "":
        res = list(set(var.split(";")))
        # list/set stuff to avoid duplicates
        # remove empty strings to avoid '-I -I' things leading to bugs
        if res.count(""):
            res.remove("")
        return res

    return []


def parse_cmake_info(path):
    """
    Parse a CMake-generated info file
    (e.g. cppimport_build_info.txt, generated by cmake)

    into a Python dictionary.

    Each line of the file has the format:
        KEY=val1;val2;val3
    Empty values are filtered out.

    Example output:
        {
            "INCLUDE_DIRS": ["/usr/include", "/usr/local/include"],
            "LIBS": ["siconos_mechanics", "siconos_kernel"],
            ...
        }
    """
    data = {}
    with open(path) as f:
        for line in f:
            if "=" in line:
                key, val = line.strip().split("=", 1)
                data[key] = [v for v in val.split(";") if v]
    return data


def format_list_multiline(values, indent=4, comment=False):
    """Format a python list in a more readable way (new lines and so on)"""
    if not values:
        return "[]"
    pad = " " * indent
    prefix = "#" if comment else ""
    joined = ",\n".join(f'{prefix}{pad}"{v}"' for v in values)
    closing = f"{prefix}]"
    return f"[\n{joined}\n{closing}"


def generate_cppimport_header(info_file, output="cppimport_header.py"):
    """
    Generate a formatted cppimport header configuration from a CMake export file.

    This function reads build information exported from CMake and writes a
    Python snippet that can be embedded inside a cppimport header (inside <%% ... %%>).

    Arguments:
    ----------
    - info_file: path to the CMake-generated cppimport_build_info.txt
    - output: path of the generated Python config file
    """
    data = parse_cmake_info(info_file)

    # Remove duplicates while preserving order
    include_dirs = list(dict.fromkeys(data.get("INCLUDE_DIRS", [])))
    #  known/standards systems dir from the include list
    # They are searched by default and keeping them leads to failure on linux
    # system during cppimport build
    system_paths = list(dict.fromkeys(data.get("SYSTEM_PATHS", [])))
    filtered_inc = [
        d
        for d in include_dirs
        if os.path.realpath(d) not in [os.path.realpath(s) for s in system_paths]
    ]
    link_dirs = format_list_multiline(list(dict.fromkeys(data.get("LINK_DIRS", []))))
    # [name.split("::")[-1] for name in data.get("LIBS", [])]
    # No cmake namespace in python outputs ...
    raw_libs = [
        name for name in data.get("LIBS", []) if "::" not in name
    ]  # , comment=True
    libs = format_list_multiline(list(dict.fromkeys(raw_libs)))
    compiler_args = data.get("FLAGS", []) + [f"-D{d}" for d in data.get("DEFINES", [])]
    # move includes to compile options, to use isystem and avoid
    # warnings from Eigen
    for path in filtered_inc:
        compiler_args.append("-isystem")
        compiler_args.append(path)
    filtered_inc = []
    compile_opts = format_list_multiline(compiler_args)
    linker_args = []
    for path in data.get("LINK_DIRS", []):
        linker_args.append("-Wl,-rpath")
        linker_args.append(path)
    linker_args = format_list_multiline(linker_args)

    header = textwrap.dedent(
        f"""\
# Auto-generated cppimport header
# You can include it inside your .cpp file like this:
#
# /*cppimport
# <%
#
# import os
# setup_pybind11(cfg)
#
# with open("cppimport_header.py") as f:
#   exec(f.read())
#
# %>
# */

# Uncomment these lines to activate verbose mode
cfg["compiler_args"] += ["-v"]
cfg["verbose"] = True
cfg['parallel'] = True
cfg["include_dirs"] += {filtered_inc}

cfg["compiler_args"] += {compile_opts}

# Libraries
# (not always needed, uncomment and complete according to your needs)
cfg["library_dirs"] += {link_dirs}
cfg["libraries"] += {libs}
cfg["linker_args"] += {linker_args}
    """
    )

    with open(output, "w") as f:
        f.write(header)
