$TEMPLATE[test_case.cpp]
//
// Copyright (c) 2003--2009
// Toon Knapen, Karl Meerbergen, Kresimir Fresl,
// Thomas Klimpel and Rutger ter Borg
//
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
// THIS FILE IS AUTOMATICALLY GENERATED
// PLEASE DO NOT EDIT!
//

#include <cstdlib>
#include <boost/numeric/bindings/$library/$levelname/$groupname.hpp>

int main(int argc, char *argv[]) {










    return EXIT_SUCCESS;
}

$TEMPLATE[end]
