#
# Siconos documentation with Doxygen 
#

# Style sheet :  Really useful ?
FILE(GLOB CSS_FILES config/css/*.* config/css/*)
FOREACH(FILE ${CSS_FILES})
  IF(NOT IS_DIRECTORY ${FILE})
    FILE(RELATIVE_PATH RFILE ${CMAKE_SOURCE_DIR} ${FILE})
    CONFIGURE_FILE(${FILE} ${CMAKE_BINARY_DIR}/${RFILE} COPYONLY)
  ENDIF(NOT IS_DIRECTORY ${FILE})
ENDFOREACH(FILE ${CSS_FILES})

# build in Generated DOCS
IF (NOT DOXYGEN_OUTPUT)
  SET(DOXYGEN_OUTPUT ${CMAKE_BINARY_DIR}/../GeneratedDocs)
ENDIF(NOT DOXYGEN_OUTPUT)


MESSAGE(STATUS "Create directory " ${DOXYGEN_OUTPUT})
FILE(MAKE_DIRECTORY ${DOXYGEN_OUTPUT})
MESSAGE(STATUS "Create directory " ${DOXYGEN_OUTPUT}/${PROJECT_SHORT_NAME})
FILE(MAKE_DIRECTORY ${DOXYGEN_OUTPUT}/${PROJECT_SHORT_NAME})
MESSAGE(STATUS "Create directory " ${DOXYGEN_OUTPUT}/Tags)
FILE(MAKE_DIRECTORY ${DOXYGEN_OUTPUT}/Tags)

# Style sheet
FILE(GLOB CSS_FILES ${CMAKE_SOURCE_DIR}/../Docs/css/*.css)
FOREACH(FILE ${CSS_FILES})
 IF(NOT IS_DIRECTORY ${FILE})
   FILE(RELATIVE_PATH RFILE ${CMAKE_SOURCE_DIR}/../Docs/css ${FILE})
   MESSAGE(STATUS "Copy " ${FILE} " to " ${DOXYGEN_OUTPUT}/${PROJECT_SHORT_NAME}/${RFILE})
   CONFIGURE_FILE(${FILE} ${DOXYGEN_OUTPUT}/${PROJECT_SHORT_NAME}/${RFILE} COPYONLY)
 ENDIF(NOT IS_DIRECTORY ${FILE})
ENDFOREACH(FILE ${CSS_FILES})


INCLUDE(TargetDoc OPTIONAL)
