IF(MSVC)
  SET(CMAKE_CXX_CREATE_SHARED_MODULE
"<CMAKE_LINKER> ${CMAKE_CL_NOLOGO} <OBJECTS> ${CMAKE_START_TEMP_FILE} /out:<TARGET> /pdb:<TARGET_PDB> /dll /version:<TARGET_VERSION_MAJOR>.<TARGET_VERSION_MINOR> <LINK_FLAGS> <LINK_LIBRARIES> ${CMAKE_END_TEMP_FILE}")
  CONFIGURE_FILE(${CMAKE_SOURCE_DIR}/scripts/cmake-vc.bat.in
    ${CMAKE_BINARY_DIR}/cmake-vc.bat)
  INSTALL(FILES ${CMAKE_BINARY_DIR}/cmake-vc.bat DESTINATION bin)
  INSTALL(FILES ${CMAKE_SOURCE_DIR}/scripts/siconos.bat DESTINATION bin)
ENDIF(MSVC)
