#!/bin/bash
#OAR --project siconos
#OAR -l /nodes=1/cpu=2/core=16,walltime=1:00:00
################################################################################
set -e
mydir=`dirname $0`
time=`which time`
timer=""
timer_args=""
python_version=`python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))'`
python_site_packages_path=`python3 -c 'import os; import sys; print(os.path.join(sys.prefix, "lib", "python" + sys.version[:4], "site-packages"))'`
venv=${VRUN_VENV:-venv}
VRUN_GUIX_CXX_TOOLCHAIN=${VRUN_GUIX_CXX_TOOLCHAIN:-clang-toolchain@18}
VRUN_GUIX_BASE_DIR=${VRUN_GUIX_BASE_DIR:-`pwd`}
case $VRUN_SETX in 1) set -x;; esac
while [ $# -gt 0 ]; do
  case $1 in

    --guix-base-dir)
      shift
      VRUN_GUIX_BASE_DIR=$1
      shift
      ;;

    --packages)
      shift
      VRUN_PACKAGES=(${1//,/ })
      shift
      ;;

    -x)
      shift
      set -x
      export VRUN_SETX=1
      ;;

    --ssh)
      shift
      host=$1
      shift
      pwd=`pwd`
      echo $PYTHONPATH
      ssh -o SendEnv=LD_LIBRARY_PATH,PYTHONPATH -x $host "cd $pwd && $0 $@"
      ;;

    --fast)
      shift
      unset GUIX_PROFILE
      export GUIX_PROFILE=$VRUN_GUIX_BASE_DIR/.siconos-guix-profile
      . ${GUIX_PROFILE}/etc/profile

      export PYTHONPATH=$GUIX_PYTHONPATH:$PYTHONPATH
      exec $0 "$@"
      ;;

    --gcc)
      shift
      export VRUN_GUIX_CXX_TOOLCHAIN=gcc-toolchain
      ;;

    --guix)
      shift
      set -x
      cat>${VRUN_GUIX_BASE_DIR}/.siconos-disks-manifest.scm<<EOF
(specifications->manifest
 '(
 "$VRUN_GUIX_CXX_TOOLCHAIN"
 "bash"
 "cuda-toolkit"
 "fclib"
 "findutils"
 "gdb"
 "git"
 "jupyter"
 "ninja"
 "parallel"
 "python"
 "python-packaging"
 "python-wheel"
 "rsync"
 "strace"
 "swig"
 "time"
 "valgrind"
 "vtk"
 "which"
 "xvfb-run"
))
EOF

      cat>${VRUN_GUIX_BASE_DIR}/.siconos-vrun-channels.scm<<EOF
;; https://guix.bordeaux.inria.fr/eval/9029823
;; 2025-10-29 13:40:39

(list (channel
        (name 'guix-science)
        (url "https://codeberg.org/guix-science/guix-science.git")
        (branch "master")
        (commit
          "bf921f7e84953f940a63b81c2ec9804d5ccaf586")
        (introduction
          (make-channel-introduction
            "b1fe5aaff3ab48e798a4cce02f0212bc91f423dc"
            (openpgp-fingerprint
              "CA4F 8CF4 37D7 478F DA05  5FD4 4213 7701 1A37 8446"))))
      (channel
        (name 'guix-science-nonfree)
        (url "https://codeberg.org/guix-science/guix-science-nonfree.git")
        (branch "master")
        (commit
          "53c488dd622d83c5c19705f0f95d48d9d5bc3720")
        (introduction
          (make-channel-introduction
            "58661b110325fd5d9b40e6f0177cc486a615817e"
            (openpgp-fingerprint
              "CA4F 8CF4 37D7 478F DA05  5FD4 4213 7701 1A37 8446"))))
      (channel
        (name 'guix-hpc)
        (url "https://gitlab.inria.fr/guix-hpc/guix-hpc.git")
        (branch "master")
        (commit
          "641e030a8bebfeaa43ca2ff12cab66763ec57aa4"))
      (channel
        (name 'guix-hpc-non-free)
        (url "https://gitlab.inria.fr/guix-hpc/guix-hpc-non-free.git")
        (branch "master")
        (commit
          "d96a225137d7934477bcf53bfab591b3b1871896"))
      (channel
        (name 'guix)
        (url "https://git.guix.gnu.org/guix.git")
        (branch "master")
        (commit
          "df23a503998a210697f49a169ab314039889515b")
        (introduction
          (make-channel-introduction
            "9edb3f66fd807b096b48283debdcddccfea34bad"
            (openpgp-fingerprint
              "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA"))))
      (channel
        (name 'guix-past)
        (url "https://codeberg.org/guix-science/guix-past.git")
        (branch "master")
        (commit
          "c3bc94ee752ec545e39c1b8a29f739405767b51c")
        (introduction
          (make-channel-introduction
            "0c119db2ea86a389769f4d2b9c6f5c41c027e336"
            (openpgp-fingerprint
              "3CE4 6455 8A84 FDC6 9DB4  0CFB 090B 1199 3D9A EBB5")))))
EOF
      # guix environment setup
      # export PATH=/var/guix/profiles/per-user/root/current-guix/bin:$PATH
      # export GUIX_DAEMON_SOCKET=guix://luke.u-ga.fr
      if [ -f /applis/site/guix-start.sh ]; then
        . /applis/site/guix-start.sh
        guix_isolation_args="--container -N --emulate-fhs --share=/tmp --share=/bettik --share=$HOME"
      else
        guix_isolation_args="--container -N --emulate-fhs --share=/tmp --share=/scratch --share=$HOME"
      fi
      rm -f ${VRUN_GUIX_BASE_DIR}/.siconos-guix-profile
      #guix_isolation_args="--pure --preserve=OMP* --preserve=VRUN*"
      guix_cmd="guix time-machine -C ${VRUN_GUIX_BASE_DIR}/.siconos-vrun-channels.scm --"
      # it seems that we need to pass explicitely the package for transformations
      exec $guix_cmd shell $guix_isolation_args \
           --root=${VRUN_GUIX_BASE_DIR}/.siconos-guix-profile \
           -m ${VRUN_GUIX_BASE_DIR}/.siconos-disks-manifest.scm \
           -D siconos \
           ${VRUN_PACKAGES} \
           -- $0 "$@"
      ;;

    --time)
      shift
      timer="$time"
      timer_args="$1"
      shift
      ;;

    --help)
      cat ${mydir}/README.md
      exit 0
      ;;

    *)
      set -x
      script=$1
      suffix="${script##*.}"
      case $suffix in py) interp=python3;; *) interp="";; esac
      shift
      args=()
      while [[ $# -gt 0 && "$1" != "--" ]]; do
        args+=("$1")
        shift
      done
      if [[ $# -gt 0 && "$1" == "--" ]]; then
        shift
        xex=""
      else
        xex="exec"
      fi
      if [ -f ${venv}/bin/activate ]; then
        . ${venv}/bin/activate
        python_version=`python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))'`
        python_site_packages_path=`python3 -c 'import os; import sys; print(os.path.join(sys.prefix, "lib", "python" + sys.version[:3], "site-packages"))'`
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/${venv}/lib/python${python_version}/site-packages/nonos/
      fi

      case "$(basename "$script")" in
        python|python3) script="$(command -v "$script")" ;;
      esac

      # Construit la commande finale comme tableau
      cmd=()
      if [ -n "$timer" ]; then
        cmd+=("$time" -f "$timer_args")
      fi
      if [ -n "$interp" ]; then
        cmd+=("$interp")
      fi
      cmd+=("$script")
      cmd+=("${args[@]}")

      if [ -n "$xex" ]; then
        exec "${cmd[@]}"
      else
        "${cmd[@]}"
      fi
      ;;
  esac
done
