#!/bin/bash
#OAR --project siconos
#OAR -l /nodes=1/cpu=2/core=16,walltime=1:00:00
################################################################################
set -e
set -x
mydir=`dirname $0`
time=`which time`
timer=""
timer_args=""
python_version=`python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))'`
python_site_packages_path=`python3 -c 'import os; import sys; print(os.path.join(sys.prefix, "lib", "python" + sys.version[:4], "site-packages"))'`
venv=${VRUN_VENV:-venv}
VRUN_GUIX_CXX_TOOLCHAIN=${VRUN_GUIX_CXX_TOOLCHAIN:-clang-toolchain}
case $VRUN_SETX in 1) set -x;; esac
while [ $# -gt 0 ]; do
  case $1 in
    --vview)
      shift
      args=$@
      set --
      . ${venv}/bin/activate
      export LD_LIBRARY_PATH=`pwd`/${venv}/lib/python${python_version}/site-packages/nonos/:$LD_LIBRARY_PATH
      exec python3 ./src/siconos/py/nonos/vview.py $args
      ;;

    -x)
      shift
      set -x
      export VRUN_SETX=1
      ;;

    --fast)
      shift
      pwd=`pwd`
      unset GUIX_PROFILE
      export GUIX_PROFILE=$pwd/.siconos-guix-profile
      . ${GUIX_PROFILE}/etc/profile

      export PYTHONPATH=$GUIX_PYTHONPATH
      exec $0 "$@"
      ;;

    --gcc)
      shift
      export VRUN_GUIX_CXX_TOOLCHAIN=gcc-toolchain
      ;;

    --guix)
      shift
      set -x
      cat>.siconos-disks-manifest.scm<<EOF
(specifications->manifest
 '( "siconos-with-vkernel" "benchmark" "$VRUN_GUIX_CXX_TOOLCHAIN" "valgrind"
    "suitesparse" "eigen" "boost" "fmt" "range-v3" "gfortran-toolchain" "cppunit" "python-pytest"
    "cmake" "ninja" "make" "bash" "coreutils" "which" "python" "python-pip" "python-numpy" 
    "python-scikit-build" "python-setuptools" "nlohmann-json" "python-wheel" "python-pytest"
    "pybind11" "strace" "jupyter" "python-ipykernel" "procps" "gdb" "git" "emacs-next"
    "time" "parallel" "findutils" "nss-certs" "rsync"))
EOF

      cat>.siconos-vrun-channels.scm<<EOF
(list (channel
        (name 'guix)
        (url "https://git.savannah.gnu.org/git/guix.git")
        (branch "master")
        (commit
          "2b2b6a7675d43ff82487718c729cfaf5edf98c8d")
        (introduction
          (make-channel-introduction
            "9edb3f66fd807b096b48283debdcddccfea34bad"
            (openpgp-fingerprint
              "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA"))))
      (channel
       (name 'guix-hpc)
       (url "https://gitlab.inria.fr/bremond/guix-hpc.git")
       (branch "add-siconosx")
       (commit
        "7e107ae4b0b75e7e0d396263a2b1df409e425697")))
EOF
      # guix environment setup
      # export PATH=/var/guix/profiles/per-user/root/current-guix/bin:$PATH
      # export GUIX_DAEMON_SOCKET=guix://luke.u-ga.fr
      [ -f /applis/site/guix-start.sh ] && . /applis/site/guix-start.sh
      pwd=`pwd`
      rm -f $pwd/.siconos-guix-profile
      #guix_isolation_args="--container -N --emulate-fhs --share=/tmp --share=/scratch --share=$HOME"
      guix_isolation_args="--pure --preserve=OMP* --preserve=VRUN*"
      guix_cmd="guix time-machine -C ./.siconos-vrun-channels.scm --"
      # it seems that we need to pass explicitely the package for transformations
      exec $guix_cmd shell $guix_isolation_args \
           --root=.siconos-guix-profile \
           -m .siconos-disks-manifest.scm \
           -- $0  "$@"
      ;;

    --venv-dir)
      shift
      venv=$1
      export VRUN_VENV=$1
      python_version=`python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))'`
      [ -f ${venv}/bin/activate ] || python${python_version} -m venv --system-site-packages --clear ${venv}
      shift
      . ${venv}/bin/activate
      python_site_packages_path=`python3 -c 'import os; import sys; print(os.path.join(sys.prefix, "lib", "python" + sys.version[:3], "site-packages"))'`
      ;;

    --time)
      shift
      timer="$time"
      timer_args="$1"
      shift
      ;;

    --help)
      cat ${mydir}/README.md
      exit 0
      ;;

    --cmake)
      shift
      . ${venv}/bin/activate
      exec $0 cmake -DPython_EXECUTABLE=`which python${python_version}` $@
      ;;

    --install)
      shift
      [ -f ${venv}/bin/activate ] || python3 -m venv --system-site-packages --clear ${venv}
      . ${venv}/bin/activate
      python_version=`python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))'`
      python_site_packages_path=`python3 -c 'import os; import sys; print(os.path.join(sys.prefix, "lib", "python" + sys.version[:4], "site-packages"))'`
      export CC=clang
      export CXX=clang++
      TMPBUILDIR=`mktemp -d /tmp/vrun-build.XXXX`
      TMPINSTALLDIR=`mktemp -d /tmp/vrun-install.XXXX`
      trap "rm -rf ${TMPBUILDIR} ${TMPINSTALLDIR}; exit" INT TERM EXIT
      cd ${TMPBUILDIR}
      cmake ${mydir}/../.. -DPython_EXECUTABLE=`which python${python_version}` -DISOLATED_INSTALL=True \
            -DSICONOS_CUSTOM_INSTALL=${TMPINSTALLDIR} \
            -DWITH_PYB11_WRAPPER=0 \
            -DWITH_TESTING=0 \
            -DWITH_BULLET=0 \
            -DWITH_FORTRAN=0 \
            -DCOMPONENTS="externals;numerics;kernel;mechanics"
      make -j16 install
      rsync -av ${TMPINSTALLDIR}/lib/python${python_version}/site-packages/nonos/ ${python_site_packages_path}/nonos
      cd -
      ;;
    --pip-install)
      shift
      python3 -m venv --system-site-packages --clear ${venv}
      . ${venv}/bin/activate

      [ -f /applis/environments/cuda_env.sh ] && . /applis/environments/cuda_env.sh 12.1

      # export CPATH=/opt/nvidia/hpc_sdk/Linux_x86_64/24.3/cuda/12.3/include:$CPATH
      # export LD_LIBRARY_PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/24.3/cuda/12.3/lib:$LD_LIBRARY_PATH
      # export PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/24.3/cuda/12.3/bin:$PATH

      CC=clang CXX=clang++ /bin/time -f '%E %M %R' pip install .

      cd ${venv}/lib/python${python_version}/site-packages/nonos
      ln -sf ../../../../../src/siconos/py/nonos/__init__.py .
      ln -sf ../../../../../src/siconos/py/nonos/bridge.py .
      ln -sf ../../../../../src/siconos/py/nonos/mechanics_run.py .
      ln -sf ../../../../../src/siconos/py/nonos/mechanics_hdf5.py .
      cd -
      ;;

    --repl)
      shift
      [ -f ${mydir}/${venv}/bin/activate ] && . ${venv}/bin/activate
      export LD_LIBRARY_PATH=`pwd`/${venv}/lib/python${python_version}/site-packages/nonos/:$LD_LIBRARY_PATH
      python3
      ;;

    --shell)
      shift
      [ -f ${mydir}/${venv}/bin/activate ] && . ${venv}/bin/activate
      export LD_LIBRARY_PATH=`pwd`/${venv}/lib/python${python_version}/site-packages/nonos/:$LD_LIBRARY_PATH
      bash -i
      ;;

    --vexport)
      shift
      siconos_vexport $@
      ;;

    --vexport-para)
      shift
      set -x
      case $1 in --nprocs) shift; nprocs=$1; shift;; *) nprocs=1;; esac
      python3 ./src/siconos/py/nonos/siconos_vexport.py --global-filter --gen-para-script=$nprocs $1 > vrun-pprocess
      chmod +x vrun-pprocess
      $time -f '%E %M' ./vrun-pprocess
      ;;

    --perf)
      shift
      script=$1
      shift
      args=""
      while [[ $# -gt 0 && "$1" != "--" ]]; do
        args="$args $1"
        shift
      done
      if [[ $# -gt 0 && "$1" == "--" ]]; then
        shift
      fi
      . ${venv}/bin/activate
      export LD_LIBRARY_PATH=`pwd`/${venv}/lib/python${python_version}/site-packages/nonos/:$LD_LIBRARY_PATH
      perf record -g --call-graph dwarf python3 $script $args
      ;;

    *)
      set -x
      script=$1
      suffix="${script##*.}"
      case $suffix in py) interp=python3;; *) interp="";; esac
      shift
      args=""
      while [[ $# -gt 0 && "$1" != "--" ]]; do
        args="$args $1"
        shift
      done
      if [[ $# -gt 0 && "$1" == "--" ]]; then
        shift
        xex=""
      else
        xex="exec"
      fi
      [ -f ${venv}/bin/activate ] && . ${venv}/bin/activate
      python_version=`python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))'`
      python_site_packages_path=`python3 -c 'import os; import sys; print(os.path.join(sys.prefix, "lib", "python" + sys.version[:3], "site-packages"))'`
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/${venv}/lib/python${python_version}/site-packages/nonos/
      if [ ! -z "$timer" ]; then
        $xex $timer -f "$timer_args" $interp $script $args
      else
        $xex $interp $script $args
      fi
      ;;
  esac
done
